FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive 

WORKDIR /app

COPY emoberta-base ./emoberta-base
COPY utils ./utils
COPY app.py ./
COPY requirements-deploy.txt ./

RUN apt update
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update
RUN apt install python3.8 python3.8-dev python3-pip -y
RUN python3.8 -m pip install --upgrade pip
RUN python3.8 -m pip install -r requirements-deploy.txt

CMD ["python3.8", "app.py", "--model-type", "emoberta-base", "--device", "cuda"]

